import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium, expect } from '@playwright/test';
const base=process.env.TANA_TEST_URL ?? 'http://127.0.0.1:4321';
await mkdir('.tmp',{recursive:true});
const browser=await chromium.launch({headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  await page.addInitScript(()=>{
    window.__transitions=0;
    const start=document.startViewTransition?.bind(document);
    if(start)document.startViewTransition=(...args)=>{window.__transitions++;return start(...args);};
  });
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base);await expect(page.locator('.asset-tile')).toHaveCount(12);
  assert.equal(await page.locator('.wrapper > *').first().getAttribute('data-pinned'),'true');
  await expect(page.locator('.wrapper img').first()).toBeVisible();
  await page.waitForFunction(()=>[...document.querySelectorAll('.wrapper img')].filter(img=>img.getBoundingClientRect().top<innerHeight).every(img=>img.complete&&img.naturalWidth>0));
  await expect(page.getByText('Make it yours. Create with friends.',{exact:false})).toBeVisible();
  assert.equal(await page.locator('.site-header nav').count(),0);
  assert.equal(await page.locator('.library-filter').count(),0);
  await expect(page.locator('.feature-caption')).toContainText('Studio is free & open source.');
  await expect(page.locator('.chatgpt-name')).toContainText('ChatGPT');
  const margins=await page.locator('.feature-download').evaluate(el=>({top:getComputedStyle(el).marginTop,bottom:getComputedStyle(el).marginBottom}));
  assert.deepEqual(margins,{top:'30px',bottom:'20px'});
  assert.equal(await page.locator('.feature-caption').evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)');
  assert.equal(await page.locator('.credit .avatar').getAttribute('src'),'/sami.png');
  await expect(page.locator('.credit-os')).toHaveText(' · studio is open source.');
  assert.equal(await page.locator('.site-footer').evaluate(el=>getComputedStyle(el).position),'fixed');
  assert.equal(await page.locator('.site-footer').evaluate(el=>Math.round(el.getBoundingClientRect().bottom)),1000);
  await page.locator('.site-footer').evaluate(el=>el.dataset.testIdentity='persisted');
  await page.screenshot({path:'.tmp/tana-library-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Switch to dark mode'}).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:'.tmp/tana-library-dark.png',fullPage:true});
  await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.getByRole('button',{name:'Switch to light mode'}).click();
  const firstOrder=await page.locator('.asset-tile').evaluateAll(els=>els.map(e=>e.getAttribute('href')));
  await page.reload();const secondOrder=await page.locator('.asset-tile').evaluateAll(els=>els.map(e=>e.getAttribute('href')));assert.notDeepEqual(firstOrder,secondOrder);
  assert.equal(await page.locator('.wrapper > *').first().getAttribute('data-pinned'),'true');
  await page.locator('.site-footer').evaluate(el=>el.dataset.testIdentity='persisted');
  await page.getByLabel('Search models').fill('robot');await page.getByRole('button',{name:'Find',exact:true}).click();
  await expect(page).toHaveURL(/\/search\?q=robot/);
  assert.equal(await page.locator('[data-pinned]').count(),0);
  await expect(page.getByLabel('Category',{exact:true})).toBeVisible();
  await expect(page.locator('.asset-tile')).toHaveCount(1);await page.getByRole('link',{name:'View Expressive robot'}).click();
  await expect(page.getByRole('heading',{name:'Expressive robot',exact:true})).toBeVisible();
  await page.waitForFunction(()=>document.querySelector('model-viewer')?.loaded,{timeout:30000});
  assert.equal(await page.locator('.site-footer').getAttribute('data-test-identity'),'persisted');
  assert.ok(await page.evaluate(()=>window.__transitions)>0,'navigation must use actual view transitions');
  assert.match(await page.locator('.model-stage').evaluate(el=>getComputedStyle(el).viewTransitionName),/^asset-/);
  await page.getByLabel('Animation', {exact:true}).selectOption('Walking');
  await expect(page.getByRole('link',{name:'Download GLB'})).toBeVisible();
  await page.getByRole('link',{name:'Back to the library'}).click();
  await expect(page.locator('.asset-tile')).toHaveCount(12);
  await page.getByRole('link',{name:'View Expressive robot'}).click();
  await page.waitForFunction(()=>document.querySelector('model-viewer')?.loaded,{timeout:30000});
  await page.getByLabel('Animation',{exact:true}).selectOption('Running');
  assert.equal(await page.locator('model-viewer').evaluate(model=>model.animationName),'Running');
  await page.emulateMedia({reducedMotion:'reduce'});await expect.poll(()=>page.locator('model-viewer').evaluate(model=>model.autoRotate)).toBe(false);
  await page.goto(base+'/admin');
  const name='UI upload '+Date.now();await page.getByLabel('Name',{exact:true}).fill(name);
  await page.getByLabel('Description',{exact:true}).fill('A robot uploaded through the actual admin form.');
  await page.getByLabel(/^3D model/).setInputFiles('.tmp/starter/robot.glb');
  await page.getByLabel(/^Thumbnail or GIF/).setInputFiles('.tmp/starter/expressive-robot.gif');
  await page.getByLabel(/^Still thumbnail/).setInputFiles('.tmp/starter/expressive-robot.png');
  await page.getByLabel(/^Tags/).fill('ui-test, robot');
  await page.getByLabel('Publish in the public library').check();
  await page.getByRole('button',{name:'Save asset',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Published. Your asset is now in the library.',{timeout:30000});
  await expect(page.locator('#model-info')).toContainText('14 animations');
  await page.screenshot({path:'.tmp/tana-admin.png',fullPage:true});
  await page.getByLabel('Description',{exact:true}).fill('Updated in the browser.');await page.getByRole('button',{name:'Save asset',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Published. Your asset is now in the library.',{timeout:30000});
  await page.getByLabel('Publish in the public library').uncheck();await page.getByRole('button',{name:'Save asset',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('Saved as a draft.',{timeout:30000});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto(base+'/download');await expect(page.getByRole('heading',{name:'Your world. Your story.'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Desktop download coming soon'})).toBeDisabled();
  assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundSize),'28px 28px, 28px 28px');
  await page.getByRole('button',{name:'Switch to dark mode'}).click();
  await page.locator('footer').getByRole('link',{name:'blog',exact:true}).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.getByRole('button',{name:'Switch to light mode'}).click();
  await page.locator('footer').getByRole('link',{name:'download',exact:true}).click();
  await page.screenshot({path:'.tmp/tana-download.png',fullPage:true});
  await page.goto(base+'/blog');await page.getByRole('link',{name:'hello world'}).click();await expect(page.getByRole('heading',{name:'hello world'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.goto(base);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.equal(await page.locator('[data-pinned]').evaluate(el=>getComputedStyle(el).position),'relative');
  await page.emulateMedia({reducedMotion:'reduce'});
  await expect(page.locator('picture source[media="(prefers-reduced-motion: reduce)"]')).toHaveCount(3);
  await page.screenshot({path:'.tmp/tana-library-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Browser passed: original grid shuffle/pinned hero, search, real 3D preview/animation, actual admin upload/edit/unpublish, download availability, blog, mobile and reduced motion.');
} finally {await browser.close();}
