// Pack-level facts: default category and theme tags. Descriptions are written from what each pack is,
// per the creator's own pack title; nothing here is inferred per model.
// key: [category, theme tags, pack subject (used in descriptions)]
export const PACKS = {
  // Kenney (CC0) — https://kenney.nl/assets
  '3d-road-tiles': ['environments', 'road,city,tile,street', 'modular city road tiles'],
  'animated-characters-protagonists': ['characters', 'animated,rigged,humanoid', 'animated humanoid characters'],
  'animated-characters-retro': ['characters', 'animated,rigged,humanoid,retro', 'retro animated characters'],
  'animated-characters-survivors': ['characters', 'animated,rigged,humanoid,survival', 'animated survivor characters'],
  'blaster-kit': ['props', 'weapon,blaster,sci-fi,shooter', 'sci-fi blasters and shooter props'],
  'blocky-characters': ['characters', 'blocky,low-poly,humanoid', 'blocky characters'],
  'brick-kit': ['props', 'brick,toy,building-blocks', 'toy building bricks'],
  'building-kit': ['environments', 'building,architecture,modular', 'modular building parts'],
  'car-kit': ['vehicles', 'car,road,vehicle', 'cars and road vehicles'],
  'castle-kit': ['environments', 'castle,medieval,fantasy,architecture', 'medieval castle parts'],
  'city-kit-commercial': ['environments', 'city,commercial,building,skyscraper', 'commercial city buildings'],
  'city-kit-industrial': ['environments', 'city,industrial,building,factory', 'industrial city buildings'],
  'city-kit-roads': ['environments', 'city,road,street,modular', 'city road pieces'],
  'city-kit-suburban': ['environments', 'city,suburban,house,building', 'suburban houses and gardens'],
  'coaster-kit': ['environments', 'roller-coaster,theme-park,track', 'roller coaster track and park parts'],
  'cube-pets': ['characters', 'animal,pet,cube,cute', 'cube-shaped pets'],
  'factory-kit': ['environments', 'factory,industrial,conveyor,machine', 'factory and conveyor parts'],
  'fantasy-town-kit': ['environments', 'town,medieval,fantasy,village', 'fantasy town buildings and props'],
  'food-kit': ['props', 'food,kitchen,meal', 'food and kitchen items'],
  'furniture-kit': ['props', 'furniture,interior,home', 'home furniture'],
  'graveyard-kit': ['environments', 'graveyard,halloween,spooky,cemetery', 'graveyard and spooky props'],
  'hexagon-kit': ['environments', 'hexagon,terrain,tile,strategy', 'hexagonal terrain tiles'],
  'holiday-kit': ['props', 'holiday,seasonal,decoration', 'holiday and seasonal props'],
  'marble-kit': ['props', 'marble,track,puzzle,game', 'marble run parts'],
  'mini-arcade': ['props', 'arcade,retro,game,machine', 'arcade machines and props'],
  'mini-arena': ['environments', 'arena,stadium,sports', 'arena and stadium pieces'],
  'mini-characters': ['characters', 'low-poly,humanoid,miniature', 'miniature characters'],
  'mini-dungeon': ['environments', 'dungeon,fantasy,modular', 'dungeon pieces'],
  'mini-forest': ['nature', 'forest,tree,woodland', 'forest scenery'],
  'mini-market': ['props', 'market,shop,store,grocery', 'market stall and shop items'],
  'mini-skate': ['environments', 'skate,park,sports,ramp', 'skatepark pieces'],
  'minigolf-kit': ['environments', 'minigolf,golf,course,sports', 'minigolf course pieces'],
  'modular-buildings': ['environments', 'building,architecture,modular,city', 'modular building sections'],
  'modular-cave-kit': ['environments', 'cave,rock,underground,modular', 'modular cave pieces'],
  'modular-dungeon-kit': ['environments', 'dungeon,fantasy,modular', 'modular dungeon pieces'],
  'modular-space-kit': ['environments', 'space,sci-fi,corridor,modular', 'modular spaceship interior pieces'],
  'nature-kit': ['nature', 'nature,outdoor,landscape', 'natural scenery'],
  'pirate-kit': ['environments', 'pirate,ship,island,nautical', 'pirate ships and island props'],
  'platformer-kit': ['environments', 'platformer,game,level', 'platform game level pieces'],
  'prototype-kit': ['props', 'prototype,blockout,greybox', 'prototyping shapes and level blockout pieces'],
  'racing-kit': ['vehicles', 'racing,track,car,motorsport', 'racing cars and track pieces'],
  'retro-fantasy-kit': ['environments', 'retro,fantasy,medieval,low-poly', 'retro fantasy scenery'],
  'retro-urban-kit': ['environments', 'retro,urban,city,low-poly', 'retro city scenery'],
  'space-kit': ['environments', 'space,sci-fi,spaceship,planet', 'space scenery and spacecraft'],
  'space-station-kit': ['environments', 'space-station,sci-fi,corridor,modular', 'space station modules'],
  'survival-kit': ['props', 'survival,camp,outdoor,tool', 'survival and camping props'],
  'tower-defense-kit': ['environments', 'tower-defense,game,strategy,tile', 'tower defense tiles, towers and enemies'],
  'toy-car-kit': ['vehicles', 'toy,car,track,racing', 'toy cars and track pieces'],
  'train-kit': ['vehicles', 'train,railway,locomotive,track', 'trains and railway pieces'],
  'watercraft-kit': ['vehicles', 'boat,ship,water,nautical', 'boats and ships'],
  // KayKit (CC0), Kay Lousberg
  'KayKit-Character-Pack-Adventures-1.0': ['characters', 'adventurer,fantasy,humanoid,low-poly', 'fantasy adventurer characters'],
  'KayKit-Character-Pack-Skeletons-1.0': ['characters', 'skeleton,undead,fantasy,low-poly', 'skeleton characters'],
  'KayKit-City-Builder-Bits-1.0': ['environments', 'city,building,street,low-poly', 'city builder buildings and street props'],
  'KayKit-Dungeon-Remastered-1.0': ['environments', 'dungeon,fantasy,low-poly,modular', 'dungeon pieces and props'],
  'KayKit-Furniture-Bits-1.0': ['props', 'furniture,interior,home,low-poly', 'furniture'],
  'KayKit-Halloween-Bits-1.0': ['props', 'halloween,spooky,seasonal,low-poly', 'Halloween props'],
  'KayKit-Medieval-Hexagon-Pack-1.0': ['environments', 'medieval,hexagon,terrain,strategy,low-poly', 'medieval hex-tile terrain and buildings'],
  'KayKit-Prototype-Bits-1.0': ['props', 'prototype,blockout,greybox,low-poly', 'prototyping bits'],
  'KayKit-Restaurant-Bits-1.0': ['props', 'restaurant,kitchen,food,low-poly', 'restaurant, kitchen and food items'],
  'KayKit-Space-Base-Bits-1.0': ['environments', 'space,base,sci-fi,low-poly', 'space base modules and props'],
  // Quaternius (CC0) — itch.io Standard packs
  'downtowncitymegakit': ['environments', 'city,downtown,urban,modular', 'downtown city buildings and street props'],
  'fantasypropsmegakit': ['props', 'fantasy,medieval,props', 'fantasy props'],
  'medievalvillagemegakit': ['environments', 'medieval,village,architecture,modular', 'medieval village architecture'],
  'modularcharacteroutfitsfantasy': ['characters', 'fantasy,outfit,modular,humanoid', 'modular fantasy character outfits'],
};
